development:
  adapter: postgresql
  encoding: unicode
  database: garuda_production
  host: localhost
  pool: 5
  username: garuda
  password: garuda

test:
  adapter: postgresql
  encoding: unicode
  database: garuda_test
  host: localhost
  pool: 5
  username: garuda
  password: garuda
